version: "3"

services:
  oracle:
    image: wnameless/oracle-xe-11g
    ports:
      - "1521:1521"
    environment:
      - ORACLE_ALLOW_REMOTE=true
    deploy:
      mode: replicated
      replicas: 1
      labels: [DB=ORACLE]
      # service resource management
      # resources:
      #   # Hard limit - Docker does not allow to allocate more
      #   limits:
      #     cpus: '0.25'
      #     memory: 512M
      #   # Soft limit - Docker makes best effort to return to it
      #   reservations:
      #     cpus: '0.25'
      #     memory: 256M
      # service restart policy
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      # service update configuration
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: continue
        monitor: 60s
        max_failure_ratio: 0.3
      # placement constraint - in this case on 'worker' nodes only
      placement:
        constraints: [node.hostname != node1]

# docker deploy --compose-file ./compose-solo.yml pws