apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mariadb
  namespace: default
  labels:
    type: db  
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - image: mariadb:10.3.0
        imagePullPolicy: IfNotPresent
        name: mariadb
        args:
          - "mysqld"
          - "--max-connections=1000"
          - "--key_buffer_size=384M"
          - "--table_open_cache=4000"
          - "--sort_buffer_size=4M"
          - "--read_buffer_size=1M"
          - "--net_buffer_length=1M"
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "test"
        ports:
        - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb
  namespace: default
spec:
  type: LoadBalancer
  ports:
  - port : 3306
    targetPort: 3306
    protocol: TCP
    name: app
  selector:
    app: mariadb