apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: percona
  namespace: default
  labels:
    type: db
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: percona
    spec:
      containers:
      - image: percona:5.7.18
        imagePullPolicy: IfNotPresent
        name: percona
        args:
          - "mysqld"
          - "--max-connections=100"
          - "--key_buffer_size=384M"
          - "--table_open_cache=4000"
          - "--sort_buffer_size=4M"
          - "--read_buffer_size=1M"
          - "--net_buffer_length=1M"
          - "--innodb_buffer_pool_size=2G"
          - "--innodb_log_file_size=1G"
          - "--innodb_flush_method=O_DIRECT"
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "test"
        ports:
        - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: percona
  namespace: default
spec:
  type: NodePort
  ports:
  - port : 3306
    targetPort: 3306
    protocol: TCP
    name: app
  selector:
    app: percona