apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: oracle
  namespace: default
  labels:
    type: db  
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: oracle
    spec:
      containers:
      - image: wnameless/oracle-xe-11g
        imagePullPolicy: Always
        name: oracle
        env:
        - name: ORACLE_ALLOW_REMOTE
          value: "true"       
        ports:
        - containerPort: 1521
---
apiVersion: v1
kind: Service
metadata:
  name: oracle
  namespace: default
spec:
  type: LoadBalancer
  ports:
  - port : 1521
    targetPort: 1521
    protocol: TCP
    name: app
  selector:
    app: oracle